services:
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "8088:8080" 
    networks:
      - pre-owned-network
    env_file:
      - .env

  brand-service:
    build:
      context: ./services/brand-service
    ports:
      - "8081:8080" 
    networks:
      - pre-owned-network
    env_file:
      - .env

  model-service:
    build:
      context: ./services/model-service
    ports:
      - "8082:8080" 
    networks:
      - pre-owned-network
    env_file:
      - .env

  storage-service:
    build:
      context: ./services/storage-service
    ports:
      - "8083:8080" 
    networks:
      - pre-owned-network
    env_file:
      - .env
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: preowned
    ports:
      - "5433:5432"
    networks:
      - pre-owned-network

  db:
    container_name: db
    image: postgres:17.3-alpine3.20
    environment:
      POSTGRES_DB: preowned
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pre-owned-network

networks:
  pre-owned-network:
    driver: bridge

volumes:
  pgdata: