services:
  auth-service:
    build:
      context: ./services/auth-service
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  brand-service:
    build:
      context: ./services/brand-service
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  model-service:
    build:
      context: ./services/model-service
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  storage-service:
    build:
      context: ./services/storage-service
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  defect-service:
    build:
      context: ./services/defect-service
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  defect_choice-service:
    build:
      context: ./services/defect_choice-service
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  phone-service:
    build:
      context: ./services/phone-service
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: preowned
    ports:
      - "5433:5432"
    networks:
      - pre-owned-network

  db:
    container_name: db
    image: postgres:17.3-alpine3.20
    environment:
      POSTGRES_DB: preowned
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pre-owned-network

networks:
  pre-owned-network:
    driver: bridge
