services:
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: dockerfile
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  brand-service:
    build:
      context: ./services/brand-service
      dockerfile: dockerfile
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  model-service:
    build:
      context: ./services/model-service
      dockerfile: dockerfile
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  storage-service:
    build:
      context: ./services/storage-service
      dockerfile: dockerfile
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  defect-service:
    build:
      context: ./services/defect-service
      dockerfile: dockerfile
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  defect_choice-service:
    build:
      context: ./services/defect_choice-service
      dockerfile: dockerfile
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  phone-service:
    build:
      context: ./services/phone-service
      dockerfile: dockerfile
    networks:
      - pre-owned-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: preowned
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pre-owned-network

networks:
  pre-owned-network:
    driver: bridge

volumes:
  pgdata: